from ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update

RUN apt-get install -y python3.11 python3.11-distutils python3.11-dev && \
    apt-get install -y python3-pip

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
    update-alternatives --set python3 /usr/bin/python3.11

RUN python3.11 -m pip install --upgrade pip setuptools wheel

WORKDIR /hub

COPY requirements/hub-base.txt ./
RUN pip install --no-cache-dir -r hub-base.txt

COPY requirements/hub-cpu.txt ./
RUN pip install --no-cache-dir -r hub-cpu.txt

# GNU/Linux
#
# PyInstaller requires the ldd terminal application to discover the shared libraries required by each program or shared library. It is typically found in the distribution-package glibc or libc-bin.
#
# It also requires the objdump terminal application to extract information from object files and the objcopy terminal application to append data to the bootloader. These are typically found in the distribution-package binutils.
RUN apt-get install -y binutils
RUN apt-get install -y libc-bin
COPY requirements/hub-builder.txt ./
RUN pip install --no-cache-dir -r hub-builder.txt

COPY . .
CMD [ "python3", "./src/hub_build_gnu_linux.py" ]
