from python:3.11

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY requirements-cpu.txt ./
RUN pip install --no-cache-dir -r requirements-cpu.txt

COPY . .

CMD [ "python", "./serve.py" ]
