from ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install software-properties-common to add PPAs
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update

# Install Python 3.11 and pip
RUN apt-get install -y python3.11 python3.11-distutils && \
    apt-get install -y python3-pip

# Update alternatives to use Python 3.11 as the default python3
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
    update-alternatives --set python3 /usr/bin/python3.11

# Ensure pip is updated and set to use the correct Python version
RUN python3.11 -m pip install --upgrade pip setuptools wheel

RUN apt-get install -y wget
RUN wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf
RUN chmod +x /usr/bin/ape
# RUN sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
# RUN sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

WORKDIR /hub

COPY requirements/hub-base.txt ./
RUN pip install --no-cache-dir -r hub-base.txt

COPY requirements/hub-cpu.txt ./
RUN pip install --no-cache-dir -r hub-cpu.txt

COPY . .


CMD [ "python3", "./src/hub.py" ]
